// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArtm1lSDdDHj0rzbBPBT4W33APn0Kavyo',
    appId: '1:1018125828963:web:2b03023cb05bd288f10956',
    messagingSenderId: '1018125828963',
    projectId: 'eventmate-61924',
    authDomain: 'eventmate-61924.firebaseapp.com',
    storageBucket: 'eventmate-61924.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVfKywQAd5KGdCIxfr72_FWjER350xjk',
    appId: '1:1018125828963:android:83806d37da458005f10956',
    messagingSenderId: '1018125828963',
    projectId: 'eventmate-61924',
    storageBucket: 'eventmate-61924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpcW9UbaVUOdkfDhBcVxNt4VHGMzgWERU',
    appId: '1:1018125828963:ios:f228a7e34efd387cf10956',
    messagingSenderId: '1018125828963',
    projectId: 'eventmate-61924',
    storageBucket: 'eventmate-61924.firebasestorage.app',
    iosClientId: '1018125828963-8dps5g025n1l6k3r2j4p3t0i7dqmju5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpcW9UbaVUOdkfDhBcVxNt4VHGMzgWERU',
    appId: '1:1018125828963:ios:f228a7e34efd387cf10956',
    messagingSenderId: '1018125828963',
    projectId: 'eventmate-61924',
    storageBucket: 'eventmate-61924.firebasestorage.app',
    iosClientId: '1018125828963-8dps5g025n1l6k3r2j4p3t0i7dqmju5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArtm1lSDdDHj0rzbBPBT4W33APn0Kavyo',
    appId: '1:1018125828963:web:3ced4886a69cfbaff10956',
    messagingSenderId: '1018125828963',
    projectId: 'eventmate-61924',
    authDomain: 'eventmate-61924.firebaseapp.com',
    storageBucket: 'eventmate-61924.firebasestorage.app',
  );

}